workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      node: latest
    scripts:
      - npm install
      - cd frontend
      - npm run build
      - npx cap sync android
    artifacts:
      - frontend/android/**/*.apk
      - frontend/android/**/*.aab
    publishing:
      email:
        recipients:
          - user@example.com

  ios-build:
    name: iOS Build
    max_build_duration: 30
    environment:
      node: latest
      xcode: "16.0"
    scripts:
      - npm install
      - cd frontend
      - npm run build
      - npx cap sync ios
    artifacts:
      - frontend/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
